---
deployment:
  tasks:
    - export DEPLOYPATH=/home/udai4354/public_html/CV
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp indexEnglish.html $DEPLOYPATH